spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    admin-chat-id: ${TELEGRAM_ADMIN_CHAT_ID}
    username: eng_vocabu_bot
    token: ${TELEGRAM_BOT_TOKEN}

dictionary:
  import-on-startup: true
  reset-before-import: false
  source-file-path: src/main/resources/dictionary.csv

logging:
  level:
    root: INFO
    tg.vocabu: DEBUG